// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SIMIKO.App.Server.Models;

public partial class JenisSKompetensi
{
    [Key]
    public int ID { get; set; }

    [Column("JenisSKompetensi")]
    [StringLength(50)]
    public string JenisSKompetensi1 { get; set; }

    public int IDmodul { get; set; }

    public bool Cstm { get; set; }

    [InverseProperty("IDjenisKompetensiNavigation")]
    public virtual ICollection<tblHasilAssesment> tblHasilAssesment { get; set; } = new List<tblHasilAssesment>();

    [InverseProperty("JenisSKompetensiNavigation")]
    public virtual ICollection<tblJabTarget> tblJabTarget { get; set; } = new List<tblJabTarget>();
}