// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SIMIKO.App.Server.Models;

public partial class JenisTahapan
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string TahapanId { get; set; }

    [Required]
    [StringLength(255)]
    public string ActionController { get; set; }
}