// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SIMIKO.App.Server.Models;

public partial class JenisKompetensi
{
    [Key]
    public int ID { get; set; }

    [Column("JenisKompetensi")]
    [StringLength(255)]
    public string JenisKompetensi1 { get; set; }

    public int IDmodul { get; set; }
}