// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SIMIKO.App.Server.Models;

public partial class tbl_Activity
{
    [Key]
    public long id { get; set; }

    [StringLength(255)]
    public string Nama { get; set; }

    [StringLength(50)]
    public string UserId { get; set; }

    [Required]
    [StringLength(255)]
    public string Action { get; set; }

    [Required]
    [StringLength(255)]
    public string Controller { get; set; }

    [StringLength(255)]
    public string Param { get; set; }

    public string Description { get; set; }

    public DateTime? EndTime { get; set; }

    public DateTime? StartTime { get; set; }

    public TimeSpan Duration { get; set; }

    [StringLength(100)]
    public string TahapanId { get; set; }

    public bool IsSent { get; set; }
}