// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SIMIKO.App.Server.Models;

public partial class tbl_pegawaiEksternal
{
    [Key]
    public int id { get; set; }

    [StringLength(18)]
    [Unicode(false)]
    public string nip { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string nip_lama { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string nama { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string nama_tanpa_gelar { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string gelar_depan { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string gelar_belakang { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string karpeg { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string tempat_lahir { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? tgl_lahir { get; set; }

    public int? kode_agama { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string agama { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string alamat { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string kota { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string kode_pos { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string telepon { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string npwp { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? tmt_pangkat { get; set; }

    [StringLength(21)]
    [Unicode(false)]
    public string jenis_pangkat { get; set; }

    [StringLength(40)]
    [Unicode(false)]
    public string no_sk_pangkat { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? tgl_sk_pangkat { get; set; }

    public int? mkg_tahun_pangkat { get; set; }

    public int? mkg_bulan_pangkat { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? tmt_jabatan { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string jabatan { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string eselon { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string no_sk_jabatan { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? tgl_sk_jabatan { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string unit_penempatan { get; set; }

    public int? kode_jabatan { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string jabatan_lengkap { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string kode_unit { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string atasan { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string tipe_jabatan { get; set; }

    public int? grade { get; set; }

    public int? kode_gender { get; set; }

    public int? kode_gol { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string golongan { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string pangkat { get; set; }

    public int? usia { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string kode_unit_2 { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string unit_eselon_2 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string kode_unit_3 { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string unit_eselon_3 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string kode_unit_4 { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string unit_eselon_4 { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string karis_karsu { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string peran { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string ukuran_baju { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string ukuran_celana { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string taspen { get; set; }

    public double? nilai_toefl { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? tgl_toefl { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string status_pegawai { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string golongan_q { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string jenis_kelamin { get; set; }

    public int? kode_pendidikan { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string pendidikan { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string nama_sekolah { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string jurusan { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? tanggal_lulus { get; set; }

    public bool? dalam_negeri { get; set; }

    [StringLength(12)]
    [Unicode(false)]
    public string lulusan { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string email { get; set; }

    public int? kode_pangkat { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string nomor_ijazah { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? tmt_eselon { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? tmt_unit { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? tmt_cpns { get; set; }
}