// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SIMIKO.App.Server.Models;

public partial class tblAssesmentUser
{
    [Key]
    public int ID { get; set; }

    public int? Periode { get; set; }

    public int? IDuser { get; set; }

    [StringLength(18)]
    public string NIPuser { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? TglAssesment { get; set; }

    [StringLength(50)]
    public string KodeJabatan { get; set; }

    public int? LamaKerja { get; set; }

    public string JabAssesment { get; set; }

    public int? KdJabExisting { get; set; }

    public int JenisAsses { get; set; }

    [ForeignKey("IDuser")]
    [InverseProperty("tblAssesmentUser")]
    public virtual tblUser IDuserNavigation { get; set; }

    [InverseProperty("IDassessmentNavigation")]
    public virtual ICollection<tblHasilAssesment> tblHasilAssesment { get; set; } = new List<tblHasilAssesment>();
}