// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SIMIKO.App.Server.Models;

public partial class tblEvaluasi
{
    [Key]
    public int ID { get; set; }

    public int? IDrenbang { get; set; }

    [Column(TypeName = "numeric(5, 2)")]
    public decimal? Skor { get; set; }

    public string Keterangan { get; set; }

    public bool Ditetapkan { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LogTgl { get; set; }
}