// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SIMIKO.App.Server.Models;

public partial class tblJabatan
{
    [Key]
    public int KodeJabatan { get; set; }

    public string NamaJabatan { get; set; }

    public bool? Target { get; set; }

    [InverseProperty("KodeJabatanNavigation")]
    public virtual ICollection<tblJabTarget> tblJabTarget { get; set; } = new List<tblJabTarget>();
}