// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SIMIKO.App.Server.Models;

public partial class tblJurnal
{
    [Key]
    public long ID { get; set; }

    public int? IDrenbang { get; set; }

    public string Realisasi { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Tanggal { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LogTgl { get; set; }

    [ForeignKey("IDrenbang")]
    [InverseProperty("tblJurnal")]
    public virtual tblRenbang IDrenbangNavigation { get; set; }

    [InverseProperty("IDjurnalNavigation")]
    public virtual ICollection<tblLogJurnal> tblLogJurnal { get; set; } = new List<tblLogJurnal>();
}