// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SIMIKO.App.Server.Models;

public partial class tblLogJurnal
{
    [Key]
    public long ID { get; set; }

    public long? IDjurnal { get; set; }

    public string Uraian { get; set; }

    public string Kendala { get; set; }

    public string Arahan { get; set; }

    public bool Diterima { get; set; }

    public bool Dikirim { get; set; }

    public bool Ditolak { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Tanggal { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LogTgl { get; set; }

    [ForeignKey("IDjurnal")]
    [InverseProperty("tblLogJurnal")]
    public virtual tblJurnal IDjurnalNavigation { get; set; }
}