// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SIMIKO.App.Server.Models;

public partial class tblPeriode
{
    [Key]
    public int ID { get; set; }

    [StringLength(255)]
    public string Periode { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? StartDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EndDate { get; set; }

    public bool Aktif { get; set; }

    [InverseProperty("IDperiodeNavigation")]
    public virtual ICollection<tblIDP> tblIDP { get; set; } = new List<tblIDP>();

    [InverseProperty("PeriodeNavigation")]
    public virtual ICollection<tblJabTarget> tblJabTarget { get; set; } = new List<tblJabTarget>();
}