// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SIMIKO.App.Server.Models;

public partial class tblRenbang
{
    [Key]
    public int ID { get; set; }

    public int? IDidp { get; set; }

    public int? IDsoftkompetensi { get; set; }

    public int? IDaktivitas { get; set; }

    public string PenjelasanAktiv { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? WaktuPelaksAwal { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? WaktuPelaksAkhir { get; set; }

    [StringLength(255)]
    public string PihakTerkait { get; set; }

    [Column(TypeName = "text")]
    public string CstmKompetensi { get; set; }

    [Column(TypeName = "text")]
    public string CstmIndikatorKomp { get; set; }

    [ForeignKey("IDidp")]
    [InverseProperty("tblRenbang")]
    public virtual tblIDP IDidpNavigation { get; set; }

    [InverseProperty("IDrenbangNavigation")]
    public virtual ICollection<tblJurnal> tblJurnal { get; set; } = new List<tblJurnal>();
}