// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SIMIKO.App.Server.Models;

public partial class tblUserBusiness
{
    [Key]
    public int ID { get; set; }

    public int? Periode { get; set; }

    public int? IDuser { get; set; }

    public int? Mtetap { get; set; }

    public int? Mtaktetap { get; set; }

    public bool? FixedMT { get; set; }

    public bool? FixedMTT { get; set; }

    public bool? KirimMT { get; set; }

    public bool? KirimMTT { get; set; }

    [ForeignKey("IDuser")]
    [InverseProperty("tblUserBusiness")]
    public virtual tblUser IDuserNavigation { get; set; }
}